### ISSUE TITLE
Liste de mots du dictionnaire pour en sélectionner un aléatoirement ?

### ISSUE THREAD

**Issue by Naereen** [VincentGuiraudou/drawsheep.me#11]
Bonjour @anmavtb,
En lisant la description de ce projet, "2. Choisir un mot" : est-ce qu'il y a quelque part dans ce projet une liste de mots pour que le programme en sélectionne un automatiquement ? (j'ai cherché, sans trouver)
Merci d'avance !

**Comment by anmavtb** [comment]
Bonjour !
Tout d'abord, désolé du temps de réponse, cela fait un moment que je n'ai pas pris le temps de consulter mon GitHub.
Il n'est pas encore prévu d'intégrer une liste de mots prédéfinis.
Chaque joueur doit choisir un mot qui va définir la difficulté du jeu : plus un mot est compliqué, plus il est difficile à dessiner et donc à trouver. De ce fait, les joueurs peuvent choisir des catégories.
Mais je pourrai intégrer une fonctionnalité pour proposer des mots si la personne ne sais pas quoi choisir.

**Comment by Naereen** [comment]
Bonjour @anmavtb,
Aucun problème pour le retard.
J'ai fini mon bébé projet, même si c'est moche, il y a ~1500 mots c'est déjà fonctionnel : https://naereen.github.io/Free-dictionnaries-for-Pictionnary/
Donc pas besoin de plus, en ce qui me concerne.
Bonne fin d'année :christmas_tree: :santa: !

**Comment by anmavtb** [comment]
Très joli travail !
Maintenant, je sais que, si j'ai besoin d'un dictionnaire de mots pour un de mes projets, je pourrai faire appel à vous 😉
Bonne fin d'année à vous aussi !
